---
swagger: "2.0"
info:
  title: openfeature-evaluation-api
  version: develop
basePath: /v1
consumes:
  - application/json

produces:
  - application/json

paths:
  /version:
    get:
      tags:
        - Version
      operationId: version
      summary: Get version of the feature-evaluation-api
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/version"

definitions:
  version:
    type: object
    properties:
      apiVersion:
        type: string
